name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.x

      - run: deno task test

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      test-server:
        image: ghcr.io/melkortf/tf2-base:latest
        ports:
          - 27015:27015/tcp
          - 27015:27015/udp
          - 27020:27020/udp
        env:
          SERVER_HOSTNAME: "test rcon server"
          PORT: 27015
          CLIENT_PORT: 27016
          STEAM_PORT: 27017
          STV_PORT: 27020
          RCON_PASSWORD: "password"
        options: --tty --add-host host.docker.internal:host-gateway

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: v2.x

      - run: deno task e2e
